version: '3'

services:
    mongo:
        image: mongo
        container_name: test-toolbox-mongo
        ports:
            - "27017:27017"
        command: mongod --noprealloc --smallfiles --dbpath /data/db --noauth
